# Add label 'hacktoberfest-accepted' to PRs that are merged
name: Auto Add Label
on:
  pull_request_target:
    types: [closed]

jobs:
  auto_add_label:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add Label
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
            -d '{"labels": ["hacktoberfest-accepted"]}'
